name: Python CI Pipeline

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  test:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2 # Checkout the repository

      - name: Set up Python
        uses: actions/setup-python@v2 # Set up Python environment
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip to the latest version
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      - name: Run Pylint
        run: |
          pylint $(git ls-files '*.py')

      - name: Run Tests
        run: |
          python -m pytest tests/

      - name: Print Success Message
        run: |
          echo "CI Pipeline completed successfully!"
          echo "========================"
          echo "✓ Code checked out"
          echo "✓ Python environment set up"
          echo "✓ Dependencies installed"
          echo "✓ Linting completed"
          echo "✓ Tests executed"
          echo "========================"
